export default {
  products: [
    {
      _id: '1',
      name: "Uncle's Cafe",
      category: 'block1',
      image: '/images/product-1.jpg',
      price: 59,
      brand: 'Food',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      open: true,
      inside: [
        {
          id: 'uncle1',
          name: 'Egg Roll',
          price: '100 Rs',
          brand: 'Food',
          image: '/images/egg_roll.jpeg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
          description: 'Fluffy Egg roll',
        },
        {
          id: 'uncle1',
          name: 'Chicken Fried Rice',
          price: '150 Rs',
          brand: 'Food',
          image: '/images/chicken_fried_rice.jpeg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
          description: 'Delicious Chicken Fried Rice',
        },
        {
          id: 'uncle1',
          name: 'Burger',
          price: '70 Rs',
          brand: 'Food',
          image: '/images/burger.jpeg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
          description: 'Sweet Burger',
        },
      ],
    },
    {
      _id: '2',
      name: '24/7 Shop',
      category: 'Hostel',
      image: '/images/product-2.jpg',
      price: 70,
      brand: 'Food',
      rating: 5,
      numReviews: 51,
      open: true,
      countInStock: 6,
      inside: [
        {
          id: 'uncle1',
          name: 'Chicken',
          price: '200 Rs',
          brand: 'Food',
          image: '/images/chicken.jpeg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
        {
          id: 'uncle1',
          name: 'Amala and Ewedu',
          price: '500 Rs',
          brand: 'Food',
          image: '/images/amala.jpeg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
        {
          id: 'uncle1',
          name: 'Pepper Soup',
          price: '200 Rs',
          brand: 'Food',
          image: '/images/pepper_soup.jpeg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
      ],
    },
    {
      _id: '3',
      name: 'Hospital Shop',
      category: 'Hospital',
      image: '/images/product-3.jpg',
      price: 59,
      brand: 'Food',
      rating: 4,
      numReviews: 45,
      open: true,
      inside: [
        {
          id: 'uncle1',
          name: 'Milkshake',
          price: '100 Rs',
          brand: 'Food',
          image: '/images/milkshake.jpeg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
        {
          id: 'uncle1',
          name: 'Ice Cream',
          price: '20 Rs',
          brand: 'Food',
          image: '/images/ice_cream.jpeg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
        {
          id: 'uncle1',
          name: 'KitKat',
          price: '50 Rs',
          brand: 'Food',
          image: '/images/kitkat.jpeg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
      ],
    },
    {
      _id: '4',
      name: 'Mandela Shop',
      category: 'Mandela',
      image: '/images/product-4.jpg',
      price: 90,
      brand: 'Food',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
      open: true,
      inside: [
        {
          id: 'uncle1',
          name: 'Sprite',
          price: '100 Rs',
          brand: 'Food',
          image: '/images/product-1.jpg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
        {
          id: 'uncle1',
          name: 'Egg Roll',
          price: '100 Rs',
          brand: 'Food',
          image: '/images/product-1.jpg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
        {
          id: 'uncle1',
          name: 'Egg Roll',
          price: '100 Rs',
          brand: 'Food',
          image: '/images/product-1.jpg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
      ],
    },
    {
      _id: '5',
      name: 'Girls Hostel Shop',
      category: 'Girls Hostel',
      image: '/images/product-5.jpg',
      price: 119,
      brand: 'Food',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
      open: true,
      inside: [
        {
          id: 'uncle1',
          name: 'Fanta',
          price: '100 Rs',
          brand: 'Food',
          image: '/images/product-1.jpg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
        {
          id: 'uncle1',
          name: 'Egg Roll',
          price: '100 Rs',
          brand: 'Food',
          image: '/images/product-1.jpg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
        {
          id: 'uncle1',
          name: 'Egg Roll',
          price: '100 Rs',
          brand: 'Food',
          image: '/images/product-1.jpg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
      ],
    },
    {
      _id: '6',
      name: 'Cocacola Shop',
      category: 'Cocacola',
      image: '/images/product-6.jpg',
      price: 85,
      brand: 'Food',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
      open: true,
      inside: [
        {
          id: 'uncle1',
          name: 'Coke',
          price: '100 Rs',
          brand: 'Food',
          image: '/images/product-1.jpg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
        {
          id: 'uncle1',
          name: 'Egg Roll',
          price: '100 Rs',
          brand: 'Food',
          image: '/images/product-1.jpg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
        {
          id: 'uncle1',
          name: 'Egg Roll',
          price: '100 Rs',
          brand: 'Food',
          image: '/images/product-1.jpg',
          category: 'Rolls',
          avaialbe: true,
          countInStock: 6,
        },
      ],
    },
  ],
};
